fix: properly filter by env
aptible/app-ui pull request #159
Opened 2023-06-20 22:33 UTC by madhuravius

no app, one db:

<img width="1005" alt="image" src="https://github.com/aptible/app-ui/assets/2961973/3272a7b3-cd35-476a-87a0-1b799e735349">

one app, no db:

<img width="1067" alt="image" src="https://github.com/aptible/app-ui/assets/2961973/ca993c1b-a579-41b4-8068-5fb4eea459d7">

one app, one db:

<img width="1031" alt="image" src="https://github.com/aptible/app-ui/assets/2961973/7c51aaa3-7d2e-44de-8881-1c86be0d88e0">

many dbs:

<img width="1069" alt="image" src="https://github.com/aptible/app-ui/assets/2961973/1840ae62-f74d-450a-9c1d-49628e3b207a">

2023-06-20 22:42 UTC, madhuravius commented on src/deploy/app/index.ts
> +    return apps.filter((app) => app.environmentId === envId);
needed because there's mutated data from parent selector that is not present for the db equiv

2023-06-20 23:17 UTC, joeclayallday approved these changes

2023-06-21 13:46 UTC, neurosnap requested changes

2023-06-21 13:46 UTC, neurosnap commented on src/deploy/app/index.ts
> +    return apps.filter((app) => app.environmentId === envId);
If you use this inside the view then it won't have all the grep filtering, right?

You can see how I did the exact same thing here: https://github.com/aptible/app-ui/blob/edda4368cc09b34568c46398372a38182e2b8fb6/src/deploy/activity/index.ts#L44

2023-06-21 13:46 UTC, neurosnap commented on src/ui/shared/app/app-list.tsx
> +      : selectAppsForTableSearch(s, {
We should make separate components for this and not branch.

You can see how I did this inside `Activity`:
https://github.com/aptible/app-ui/blob/edda4368cc09b34568c46398372a38182e2b8fb6/src/ui/shared/activity.tsx#L212

Another reason to no use the global `AppList` component is so we can be more surgical with what we fetch.  For an `AppList` scoped to a single `Account` we should use an endpoint that fetches just those apps.

2023-06-21 13:46 UTC, neurosnap commented on src/ui/shared/db/database-list.tsx
> +    environmentId
Same thing here.

2023-06-21 13:57 UTC, madhuravius commented on src/deploy/app/index.ts
> +    return apps.filter((app) => app.environmentId === envId);
understood, yeah i'll enforce it's a search result on the view as well (bad mistake on my part)

2023-06-21 19:52 UTC, madhuravius commented on src/ui/shared/resource-list-view.tsx
> +  header?: ReactNode;
https://stackoverflow.com/questions/58123398/when-to-use-jsx-element-vs-reactnode-vs-reactelement

this must be because there are situations where the header can be nil/empty apparently from the existing code

2023-06-21 21:42 UTC, madhuravius commented
So it looks like we're going to:

* break up apps/dbs on env page
* add a bunch of new data points on those tables
* drop search on the env specific views (and links to the same env)

2023-06-22 01:02 UTC, madhuravius commented
@joeclayallday after recent changes:

<img width="1269" alt="image" src="https://github.com/aptible/app-ui/assets/2961973/b0eefa94-e0c1-4617-8d3d-0ef7d85572b7">

dbs list:

<img width="1257" alt="image" src="https://github.com/aptible/app-ui/assets/2961973/66186562-20b6-425c-b21e-d9ee1615b86b">

apps list:

<img width="1296" alt="image" src="https://github.com/aptible/app-ui/assets/2961973/938d99d5-bd46-4d53-9a45-8a72be82830b">

dbs in env:

<img width="1275" alt="image" src="https://github.com/aptible/app-ui/assets/2961973/064899f4-7efa-4446-bcc2-1def621cc6dc">

apps in env:

<img width="1234" alt="image" src="https://github.com/aptible/app-ui/assets/2961973/2b566680-98ab-42e0-98c4-dd76ed503f0f">

2023-06-22 01:34 UTC, joeclayallday approved these changes

2023-06-22 02:38 UTC, madhuravius commented
@neurosnap  on the note of overly nestedness/lots of complexity on the views for the lists

i'm wrapping up comparable tables with similar layout issues eric, so i can pull a lot of the common elements (placeholder empty table, others) into common shared components and add them to styles later tomorrow evening

2023-06-22 18:50 UTC, neurosnap approved these changes

2023-06-22 18:51 UTC, merged