chore: dropped underline decoration on logs link
aptible/app-ui pull request #160
Opened 2023-06-20 22:49 UTC by madhuravius

<img width="101" alt="image" src="https://github.com/aptible/app-ui/assets/2961973/e27761ea-2254-468c-acf6-2b78c592f689">

2023-06-20 23:17 UTC, joeclayallday approved these changes

2023-06-21 13:57 UTC, neurosnap requested changes

2023-06-21 13:57 UTC, neurosnap commented on index.html
> +    <title>Aptible</title>
Non-blocker, just noting: We should probably start thinking about adding a react head component like https://github.com/nfl/react-helmet

2023-06-21 13:57 UTC, neurosnap commented on src/ui/layouts/environment-detail-layout.tsx
>  const environmentDetailBox = ({
What's the rationale for this formatting?  This is just a react component, it should be treated as such.

2023-06-21 13:57 UTC, neurosnap commented on src/ui/layouts/environment-detail-layout.tsx
> +}): React.ReactElement => {
This return type in unnecessary.

2023-06-21 13:57 UTC, neurosnap commented on src/ui/layouts/environment-detail-layout.tsx
> +    <div className={cn(tokens.layout["main width"], "py-6 -mt-5 -mb-5")}>
These negative margins are a smell, we should pair on removing them.

2023-06-21 13:57 UTC, neurosnap commented on src/ui/layouts/environment-detail-layout.tsx
> +        <div className="flex w-1/1">
`w-1/1` is not a thing as far as I can tell.  What are you trying to accomplish here?

2023-06-21 13:58 UTC, madhuravius commented on index.html
> +    <title>Aptible</title>
yeah i spoke to joe about this and that's not a bad idea (there's ways to do this with react router as well (maybe using that lib))

2023-06-21 13:58 UTC, neurosnap commented on src/ui/layouts/environment-detail-layout.tsx
>        detailsBox={environmentDetailBox({
This should just be a react component.

2023-06-21 13:58 UTC, madhuravius commented on src/ui/layouts/environment-detail-layout.tsx
> +}): React.ReactElement => {
IDE was complaining, so I was forced to in this case (inference wasn't working properly), i can try again after resetting local lang serv

2023-06-21 13:59 UTC, madhuravius commented on src/ui/layouts/environment-detail-layout.tsx
> +    <div className={cn(tokens.layout["main width"], "py-6 -mt-5 -mb-5")}>
agreed, don't remember doing this, i will check again

2023-06-21 13:59 UTC, madhuravius commented on src/ui/layouts/environment-detail-layout.tsx
> +        <div className="flex w-1/1">
copy pasta and likely mistake, i should search for other occurrences

2023-06-21 14:00 UTC, madhuravius commented on src/ui/layouts/environment-detail-layout.tsx
> +          <div className="flex-col w-1/3">
we can drop it, but it was from multicol support here (which we can use with flex too):

<img width="1043" alt="image" src="https://github.com/aptible/app-ui/assets/2961973/020c8ea1-8c08-4b8b-a93d-0c1b18f80d6b">

2023-06-21 14:01 UTC, madhuravius commented on src/ui/layouts/environment-detail-layout.tsx
> +    latestOperation.userName.length >= 15
i copy pastaed this from an existing activity page, ill update it in both from your js handles it properly suggestion (since it seems easiest to read)

2023-06-21 14:13 UTC, madhuravius commented on src/ui/layouts/environment-detail-layout.tsx
> +          <div className="flex-col w-1/3">
we're coming back to this

2023-06-21 15:28 UTC, neurosnap approved these changes

2023-06-21 15:45 UTC, merged