[WIP]style-tweaks-jc
aptible/app-ui pull request #168
Opened 2023-06-23 18:36 UTC by joeclayallday

Various Style Tweaks

2023-06-26 13:14 UTC, neurosnap requested changes
Tests are failing, probably just need to run `yarn fmt`

2023-06-26 13:14 UTC, neurosnap commented on src/ui/pages/styles.tsx
> +    <br />
In general I would recommend not using `<br />` and instead opt for using margins.

2023-06-26 17:16 UTC, joeclayallday commented on src/ui/pages/styles.tsx
> +    <br />
Sounds good!

2023-06-26 17:37 UTC, joeclayallday commented on src/ui/pages/styles.tsx
> +    <br />
Done, i removed all the HRs from the styles page and used `space-X`classNames instead, works like a charm

2023-06-27 16:05 UTC, joeclayallday commented
All the table counts are spaced evenly with search boxes aligned left:
<img width="539" alt="Screen Shot 2023-06-27 at 11 04 45 AM" src="https://github.com/aptible/app-ui/assets/4295811/5802f212-841f-4346-87f1-45a1a4ea0633">
<img width="682" alt="Screen Shot 2023-06-27 at 11 04 48 AM" src="https://github.com/aptible/app-ui/assets/4295811/019db4ae-1de2-4611-a994-61f92ea81838">
<img width="627" alt="Screen Shot 2023-06-27 at 11 04 51 AM" src="https://github.com/aptible/app-ui/assets/4295811/e7a022ab-6a0f-436e-a6ff-b549b9f8ac0f">
<img width="598" alt="Screen Shot 2023-06-27 at 11 05 08 AM" src="https://github.com/aptible/app-ui/assets/4295811/70ba5c97-dfc2-49d8-bf65-6dcdedb8289e">
<img width="666" alt="Screen Shot 2023-06-27 at 11 04 27 AM" src="https://github.com/aptible/app-ui/assets/4295811/60d8fb99-8f2c-4ea3-8d2c-8ed04c7e2433">
<img width="768" alt="Screen Shot 2023-06-27 at 11 04 33 AM" src="https://github.com/aptible/app-ui/assets/4295811/a3ba8ece-31e0-436f-ab28-c4a2cba47438">
<img width="679" alt="Screen Shot 2023-06-27 at 11 04 42 AM" src="https://github.com/aptible/app-ui/assets/4295811/0c43ec6d-5f61-45bb-b066-a836089a5f98">

2023-07-05 16:49 UTC, madhuravius commented on src/ui/layouts/hero-bg-layout.tsx
> +        marginLeft: "-2rem",
we probably shouldn't do this here, can chat w/ you about what you wanna do (there's tailwind classes for this for example) OR we can toggle this somewhere else

2023-07-05 16:56 UTC, joeclayallday commented on src/ui/layouts/hero-bg-layout.tsx
> +        marginLeft: "-2rem",
It works! Thanks!

2023-07-05 17:20 UTC, madhuravius approved these changes

2023-07-05 17:21 UTC, merged