Add Security Dashboard link to Nav
aptible/app-ui pull request #243
Opened 2023-08-02 20:41 UTC by joeclayallday

Todo
• Configure correct URL path for this variable `export const SECURITY_DASHBOARD_PATH = "/search";`
(Right now its just pointing to the search page)
• Make the link navigate users to deploy-ui's security & compliance dashboard, and when they click back in the browser take them back inside app-ui (maybe we want to open this up in a new tab?)

<img width="291" alt="Screen Shot 2023-08-02 at 3 38 44 PM" src="https://github.com/aptible/app-ui/assets/4295811/bfa8695d-412a-412c-9b97-f106f103780f">

2023-08-03 14:37 UTC, neurosnap requested changes

2023-08-03 14:37 UTC, neurosnap commented on src/ui/shared/application-sidebar.tsx
> +    { name: "Security & Compliance", to: securityDashboardUrl(), icon: <IconShield /> },
I think we want to link directly to dashboard https://dashboard.aptible.com/controls

2023-08-03 14:37 UTC, neurosnap commented on src/routes/index.ts
> +export const securityDashboardUrl = () => SECURITY_DASHBOARD_PATH;
I don't think we'll need these as we want to link directly to deploy-ui

2023-08-03 17:19 UTC, joeclayallday commented on src/routes/index.ts
> +export const securityDashboardUrl = () => SECURITY_DASHBOARD_PATH;
Thanks!

2023-08-03 17:19 UTC, joeclayallday commented on src/ui/shared/application-sidebar.tsx
> +    { name: "Security & Compliance", to: securityDashboardUrl(), icon: <IconShield /> },
Thanks!

2023-08-03 20:00 UTC, madhuravius commented on src/routes/index.ts
> +  "https://dashboard.aptible.com/controls";
not sure if you want to do this but there's a slightly different value by env and we could make it easier for staging envs to go to their appropriate link (not that it matters too much for now)

2023-08-03 20:01 UTC, madhuravius reviewed
lgtm, i think we could update that link for staging though if we wanted to (probably not worth the effort as we don't really establish staging security dashboards in most staging envs, right @neurosnap ?)

2023-08-04 14:55 UTC, neurosnap approved these changes

2023-08-04 15:37 UTC, madhuravius approved these changes

2023-08-04 16:33 UTC, merged