chore: updated activity for metric/log drains
aptible/app-ui pull request #274
Opened 2023-08-16 17:42 UTC by madhuravius

<img width="1101" alt="image" src="https://github.com/aptible/app-ui/assets/2961973/57e79e7d-2fd3-415b-972c-794a551e976c">

2023-08-16 17:43 UTC, joeclayallday approved these changes

2023-08-16 17:44 UTC, madhuravius commented on src/initial-data/index.ts
> +      // TODO - Below need to be updated on backend endpoints for proceeding
@neurosnap contingent on possible controversial backend changes, see slack eng chan for details

2023-08-21 19:17 UTC, neurosnap requested changes
Looks good to me!

Please add handlers for `/metric_drains` and `/log_drains`

![Screenshot 2023-08-21 at 3 16 37 PM](https://github.com/aptible/app-ui/assets/1940365/65f85c35-b237-403c-b3bc-a4d31c5add15)

2023-08-22 02:03 UTC, neurosnap approved these changes
nice!

2023-08-22 07:20 UTC, merged