Show-IDs-on-Tables-jc
aptible/app-ui pull request #387
Opened 2023-09-19 17:12 UTC by joeclayallday

Stacks

<img width="453" alt="Screenshot 2023-09-19 at 12 11 02 PM" src="https://github.com/aptible/app-ui/assets/4295811/14330043-8d2d-4144-a603-5bb27c6a93ca">
<img width="400" alt="Screenshot 2023-09-19 at 12 10 57 PM" src="https://github.com/aptible/app-ui/assets/4295811/e2420910-9840-4eae-a86a-b171e6adbd16">

2023-09-19 19:31 UTC, neurosnap requested changes

2023-09-19 19:31 UTC, neurosnap commented on src/ui/layouts/environment-detail-layout.tsx
> +            </Tooltip>
We should create a new `src/ui/shared/copy.tsx` component that abstracts this logic.

2023-09-19 19:41 UTC, joeclayallday commented on src/ui/layouts/environment-detail-layout.tsx
> +            </Tooltip>
Yea idk how to do that, but feel free to refactor

2023-09-20 01:25 UTC, closed without merging

2023-09-20 01:27 UTC, joeclayallday commented
Closing for now, until we get the copy component, and Idk if we need to add it to every table and header detail card until 3+ ppl ask for it.