feat: activity/services/endpoints lists - sc-10735, sc-10736 sc-10180 (app/database/environment) (part 3 - focus on envs)
aptible/app-ui pull request #41
Opened 2023-03-30 04:46 UTC by madhuravius

TODOs/questions to answer:

- [ ] correct cli copy button (gives wrong command for logs)
- [ ] change "Resources/Overview" to endpoints where applicable (dbs screen i think)
- [ ] rehydrate data on initial load (on all the layout screens?)
- [ ] validate settings page (you can't really change env type from shared -> dedicated)
- [ ] should we drop integrations/certificates tab until we're ready?
- [ ] we probably want to give the resource list views a little more love and match it closer to designs

Resources List

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/2961973/228731755-560a3393-998d-4229-89df-e34a70d5268a.png">

Activity

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/2961973/228731736-d252c66c-f9eb-443f-825b-916da09010ba.png">

Backups List

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/2961973/228731718-ee3493bc-e9e7-44bc-a48f-da92eebc1875.png">

Settings

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/2961973/228731692-a1925e7d-0a41-416b-a5ce-f15f7595b6de.png">

2023-03-30 15:50 UTC, madhuravius commented on src/deploy/endpoint/index.ts
> +export const selectEndpointsByEnvironmentId = createSelector(
leave a todo here so we can create a backend ticket for this later

2023-04-06 15:17 UTC, neurosnap requested changes
It seems like a lot of unrelated code got deleted, any idea what's going on?

2023-04-06 15:17 UTC, neurosnap commented on src/deploy/metric-drain/index.ts
> +const slice = createTable<DeployMetricDrain>({
I have some ideas on how to remove some of this boilerplate.  We should work on this eventually.

2023-04-06 15:17 UTC, neurosnap commented on src/projects/index.ts
> -    // Trigger configure operation now so we can store the env vars
Why was this deleted?

2023-04-06 15:17 UTC, neurosnap commented on src/projects/index.ts
> -export const redeployApp = thunks.create<{
why was this deleted?

2023-04-06 15:17 UTC, neurosnap commented on src/ui/pages/create-project-git.tsx
> -          {retry ? (
Why was this deleted?

2023-04-06 15:17 UTC, neurosnap commented on src/ui/pages/create-project-git.tsx
> -  const retry = () => {
Why was this deleted?

2023-04-06 15:17 UTC, neurosnap commented on src/ui/shared/db/backup-list.tsx
> +} from "../";
Pull these from the actual module files instead of the root.  The reason is for creating a better module dependency graph.

2023-05-03 14:51 UTC, closed without merging