refactor selectActivityByApp to include services
aptible/app-ui pull request #459
Opened 2023-10-02 17:43 UTC by grrowe

Had a bug (https://aptible.zendesk.com/agent/tickets/49443) where the App's activity page would not show the services activity as well ie the scale operations from the service.

- Refactor `ActivityByApp` to include the App's services as well.

2023-10-02 17:48 UTC, joeclayallday approved these changes

2023-10-02 17:49 UTC, neurosnap requested changes
Unfortunately, this is more complicated because we aren't polling for service operations on this page so the data will be stale immediately.  We also can't easily poll each service individually so I think to do this the right way would be to ensure when fetching app operations we also get service operations.

2023-10-02 17:56 UTC, neurosnap commented
Continuing discussion in Slack: https://aptible.slack.com/archives/C022BUSK487/p1696269097698449

2023-11-01 14:38 UTC, neurosnap commented
![Screenshot 2023-11-01 at 10 31 54 AM](https://github.com/aptible/app-ui/assets/1940365/3da7bec7-c9b2-47d5-b76a-6287fb4d03b2)

2023-11-01 14:38 UTC, neurosnap approved these changes

2023-11-01 14:41 UTC, joeclayallday approved these changes

2023-11-01 14:43 UTC, merged