add tuna metrics on support form
aptible/app-ui pull request #479
Opened 2023-10-04 19:22 UTC by grrowe

2023-10-04 19:25 UTC, neurosnap requested changes
I just recently formalized how we use tuna in `app-ui` which ensures we use it properly.

2023-10-04 19:25 UTC, neurosnap commented on src/ui/pages/support.tsx
> +    const w = window as any;
```ts
import { tunaEvent } from "@app/tuna";
// ...
tunaEvent('submittedAppUiSupportForm', `{ "viewedDocs": "${viewedSuggestion}", "email": "${user.email}" }`);
```

2023-10-04 19:25 UTC, neurosnap commented on src/ui/pages/support.tsx
> +                                  w.aptible.event('usedSupportSuggestion', `{ "suggestedUrl": "${hit.url}", "email": "${user.email}" }`);
same here

2023-10-04 19:26 UTC, neurosnap commented on src/ui/pages/support.tsx
> +    const w = window as any;
I don't think the data needs to be a string either

2023-10-04 19:54 UTC, grrowe commented on src/ui/pages/support.tsx
> +    const w = window as any;
Needs to be a string.
![image](https://github.com/aptible/app-ui/assets/54414856/8a61a3c0-d267-4653-a317-fe8b36a9058c)
First is as a string, second as an object

2023-10-04 20:10 UTC, neurosnap commented on src/ui/pages/support.tsx
> +      `{ "viewedDocs": "${viewedSuggestion}", "email": "${user.email}" }`,
`JSON.stringify({ viewedDocs, email })`

2023-10-04 20:23 UTC, grrowe commented on src/ui/pages/support.tsx
> +      `{ "viewedDocs": "${viewedSuggestion}", "email": "${user.email}" }`,
This encodes with the strange `"{ \"suggestedUrl\": \"https://www.aptible.com/docs/influxdb-metric-drain\", \"email\": \"graham.rowe@aptible.com\" }"` as well as not being able to use JSON selectors (`event_value::json->>'email') in postgres.

2023-10-05 02:12 UTC, neurosnap commented on src/ui/pages/support.tsx
> +      `{ "viewedDocs": "${viewedSuggestion}", "email": "${user.email}" }`,
got it, thanks for explanation!

2023-10-06 17:58 UTC, joeclayallday approved these changes

2023-10-06 18:00 UTC, neurosnap approved these changes

2023-10-06 18:01 UTC, merged