fix(app.config): multiline env var quoting value behavior
aptible/app-ui pull request #528
Opened 2023-10-20 20:56 UTC by neurosnap

2023-10-22 17:35 UTC, joeclayallday approved these changes

2023-10-23 18:09 UTC, joeclayallday approved these changes

2024-01-05 17:30 UTC, joeclayallday approved these changes

2024-01-05 18:23 UTC, joeclayallday approved these changes

2024-01-05 20:42 UTC, joeclayallday approved these changes

2024-01-08 16:43 UTC, joeclayallday approved these changes

2024-01-11 16:24 UTC, joeclayallday approved these changes

2024-01-11 19:04 UTC, joshraker commented
I'm happy to review this but I feel like we could mitigate any risk of having to come back to this again if we modify the configuration page to show a key text input and value text area input for each entry instead of trying to put the entire config into a single text area.

My understanding was that the text area was easier to implement when trying to get `app-ui` up and running but I feel we're at a point now where we could dedicate some time to this, right? I'd be happy to work on it.

2024-01-11 20:53 UTC, joshraker requested changes
I think we need to discuss how we expect the configuration input to be used. The tests suggest that we may want to support pasting a `.env` file but our solution does not interpret quotes and escape sequences the same as a shell so it won't work in every case. If we did make it work the same as a shell, users not familiar with shell syntax will likely find the interface difficult to use since any quotes or apostophes would need to be escaped. I would think we'd want to err on the side of the unfamiliar as those users are who I'd expect to use the UI over the CLI.

2024-01-11 20:53 UTC, joshraker commented on src/string-utils/index.ts
> +        value: stripQuote(value.trim()),
I feel like this approach to handling quotes is problematic. It's like it's trying to mimic how a shell would handle quotes in order to allow leading and trailing whitespace and newlines in the value, but it also keeps the quotes as part of the value, except the leading and ending quotes, as though to allow quotes to appear in the middle of the value without the need to escape them. To me, this feels like an attempt to accommodate those familiar with shell syntax and those not familar with it but the result is something that's likely to be confusing to both. Or we only intended to treat outer quotes as special and just didn't implement it that way.

The problem is quotes in the middle of the value are still looked at when determining whether or not to keep newlines in the value so if an apostrophe (single quote) appears in the value it will look for the closing single quote across lines. Even if the single quote is wrapped in double quotes like you would do to "escape" it in a shell `"'"` it will still look for the closing single quote since there's no check for surrounding double quotes and visa versa.

2024-01-11 20:53 UTC, joshraker commented on src/string-utils/index.ts
> +        value: stripQuote(value.trim()),
Tested Examples:

```
NOT_MULTI_LINE=Don't Hello
WORLD=world'

# JSON result
"NOT_MULTI_LINE": "Don't Hello\nWORLD=world"
```

```
JUST_TRY_TO_ESCAPE=Escape '"' double quote
ESCAPE=true"

# JSON result
"JUST_TRY_TO_ESCAPE": "Escape '\"' double quote\nESCAPE=true"
```

2024-01-11 20:54 UTC, joshraker commented on src/deploy/configuration/env-vars.test.ts
> +describe("configEnvToStr", () => {
This is correct we do not handle any escape sequences.

2024-01-11 21:21 UTC, neurosnap commented
The goal was to support pasting `.env` files directly into the text box.  Having each env var separated by an input / textbox is not great UX -- managing each variable is cumbersome for us and the user -- and there are gotchas with that approach as well.  For example, deleting a variable requires zeroing it out (so the API knows to remove it) so now we have to track **changes** instead of simply "these are all the variables we want."

I was basically modeling the features based on the popular https://github.com/motdotla/dotenv

We could just use their parser if that's easier.  An alternative approach would be to implement what `.env` does for docker compose: https://docs.docker.com/compose/environment-variables/env-file -- but probably skip interpolation.

Happy to entertain whatever approach we want, but to be clear: what we have in production now is worse than what we have in this PR.

2024-01-11 22:16 UTC, joshraker commented
Thanks for that context. I forgot that the fact that some users have access to change environment variables but not see them makes tracking changes much more complicated. I am in favor of using an existing library to handle dotenv parsing.

Is the main improvement that quotes are stripped from the beginning and the end of the value so that they don't appear in multiline values? I agree that's an improvement but a side effect of these changes is that a value that already has quotes at the beginning or the end will see them stripped when they're fetched and saved.

What concerns me more is the introduction of treating single quotes in the same way as double quotes. A single single quote is much more likely to appear in a config value as an apostrophe and end up merging values unexpectedly. If we were to remove that change I'd be ok signing off on this for now.

2024-01-22 14:50 UTC, joshraker commented on src/deploy/configuration/env-vars.test.ts
> +          defaultTextVal("SOMETHING", "do you even?"),
Wrapped values still aren't handled symmetrically which is why the surrounding quotes had to be removed from the two examples in [this commit](https://github.com/aptible/app-ui/pull/528/commits/265b93c90ff1306f67fe30df598693c80bc965ad#diff-bdc273a39136c93de8f8961dc4f6db4e5761975c175225b240a933d2c30b1234) to get it passing. I'm ok with shipping this as-is as long as we're committed to following up with another PR to fix how we handle quotes.

2024-01-22 14:56 UTC, joshraker approved these changes
Approved contingent on following up with a fix for handling quotes.

2024-01-22 15:34 UTC, merged