Feat: add autoscaling column to services
aptible/app-ui pull request #582
Opened 2023-11-15 22:40 UTC by joeclayallday

Todo
• Wire up the logic to properly show if a Service is Enabled or Disabled

Mockup
<img width="1400" alt="1-App" src="https://github.com/aptible/app-ui/assets/4295811/01498982-14cb-4338-abb6-d3f0c9fbba10">

2023-11-15 22:52 UTC, joeclayallday commented
I'm guessing the logic will be something similar to this

`{user.otpEnabled ? "Enabled" : "Disabled"}`

But `user.otpEnabled` with your own code.

2023-11-17 21:52 UTC, aguilinger commented
I think this will be sufficient?

2023-11-21 15:50 UTC, almathew commented
@joeclayallday happy to review if you want to move this out of draft

2023-11-21 17:12 UTC, neurosnap requested changes

2023-11-21 17:12 UTC, neurosnap commented on src/ui/shared/app/services-detail.tsx
> +  >(fetchServiceSizingPoliciesByServiceId({ service_id: service.id }));
This should probably be a hook so we can prevent a bunch of optional chaining everywhere.

2023-11-21 19:12 UTC, neurosnap commented
Closing in favor of: https://github.com/aptible/app-ui/pull/597

2023-11-21 19:12 UTC, closed without merging