Security validation fixes
aptible/app-ui pull request #714
Opened 2024-02-02 18:44 UTC by grrowe

- https://aptible.zendesk.com/agent/tickets/50991
- https://aptible.zendesk.com/agent/tickets/50992

- Added validation to forgot-pass, signup, and edit name
- Added sanitize function to remove harmful characters
- Modified invalid_email response from forgot-pass to show a `fakeTrue` so a potentially harmful user cannot know whether an email is a user.

2024-02-02 18:49 UTC, joeclayallday approved these changes

2024-02-02 18:56 UTC, neurosnap requested changes
Thanks so much for these fixes!  Let's write some automated tests for them, happy to help pair or collaborate on writing them.

2024-02-02 18:56 UTC, neurosnap commented on src/ui/pages/forgot-pass.tsx
> +                onChange={(e) => setEmail(sanitizeInput(e.currentTarget.value))}
Let's get a test written for this change.

2024-02-02 18:56 UTC, neurosnap commented on src/ui/pages/settings-profile.tsx
> +  }
Let's add a test for this change.

2024-02-02 18:56 UTC, neurosnap commented on src/ui/pages/signup.tsx
Let's write a test for this change

2024-02-02 21:07 UTC, neurosnap requested changes
Looks pretty good!  I have 2 follow up changes

2024-02-02 21:07 UTC, neurosnap commented on src/ui/pages/forgot-pass.test.tsx
> +  it("should hide a User not found email", async () => {
This one we actually need to create a stub response that includes the `invalid_email` error:

```ts
server.use(
  rest.post(`${testEnv.authUrl}/password/resets/new`, (_, res, ctx) => {
    return res(ctx.json({ error: "invalid_email" }));
  }),
);
```

2024-02-02 21:07 UTC, neurosnap commented on src/ui/pages/settings-profile.test.tsx
> +describe("ForgotPassPage", () => {
Name here doesn't match the test file

2024-02-02 21:09 UTC, neurosnap commented on src/auth/pass.ts
> +        };
While testing, make sure this code path is getting hit

2024-02-05 16:51 UTC, neurosnap approved these changes

2024-02-06 15:58 UTC, merged