feat(stack): show self_hosted stacks with aws account id
aptible/app-ui pull request #744
Opened 2024-03-01 19:42 UTC by neurosnap

Depends on: https://github.com/aptible/deploy-api/pull/1391

2024-03-01 21:46 UTC, joshraker reviewed
Looks good code-wise. Still need to pull it down and take a look at it.

2024-03-04 20:12 UTC, joshraker requested changes

2024-03-04 20:12 UTC, joshraker commented on src/ui/layouts/stack-detail-layout.tsx
> +    return `${capitalize(stackType)} (${stack.awsAccountId})`;
`capitalize` won't cut it. `self_hosted` will become `Self_hosted`. I'd just hardcode it since we're specifically checking the string.

```suggestion
    return `Self-Hosted (${stack.awsAccountId})`;
```

2024-03-04 20:15 UTC, eabruzzese approved these changes

2024-03-05 19:10 UTC, merged