add primary db link in header for replicas
aptible/app-ui pull request #923
Opened 2024-08-22 15:54 UTC by benjodo

https://app.shortcut.com/aptible/story/26534/the-cluster-tab-only-shows-replicas

2024-08-22 21:10 UTC, joeclayallday approved these changes

2024-08-23 13:22 UTC, neurosnap requested changes

2024-08-23 13:22 UTC, neurosnap commented on src/ui/layouts/database-detail-layout.tsx
> +        {databasePrimary?.id && (
With most of our selectors (like `selectDatabaseById`), we guarantee the object will exist with the correct properties.  So you don't need the `?.` in this case, just `.`.

2024-08-23 20:42 UTC, benjodo commented on src/ui/layouts/database-detail-layout.tsx
> +        {databasePrimary?.id && (
accepted/changed 👍

2024-08-26 17:07 UTC, neurosnap approved these changes

2024-08-26 17:31 UTC, merged