Improve backup load performance and show spinner until estimate is calculated
aptible/app-ui pull request #924
Opened 2024-08-23 20:34 UTC by joshraker

2024-08-26 17:07 UTC, neurosnap requested changes

2024-08-26 17:07 UTC, neurosnap commented on src/ui/shared/db/database-list.tsx
> +  if (fetchBackups) {
You can't have a hook inside of a conditional

2024-08-26 17:09 UTC, joshraker commented on src/ui/shared/db/database-list.tsx
> +  if (fetchBackups) {
You can as long as the condition doesn't change. Or is that just the only time that react won't yell at you?

2024-08-26 18:30 UTC, neurosnap commented on src/ui/shared/db/database-list.tsx
> +  if (fetchBackups) {
Yeah I would avoid it

2024-08-27 14:19 UTC, neurosnap approved these changes
Looks good.  I would say that this feels really complex for the FE to handle and we should push to do more of this work on the BE.

2024-08-27 14:20 UTC, merged